### ISSUE TITLE
Problem with LYWSD03MMC and Zigbee2Mqtt

### ISSUE THREAD

**Issue by DST73** [devbis/z03mmc#132] opened 2024-03-11 10:57 UTC
Hi,

I have flashed the Zigbee-Firmware and was able to connect it to Zigbee2Mqtt but it only show battery and linkquality
![grafik](https://github.com/devbis/z03mmc/assets/122279682/56da3405-afef-4b6e-a867-79369056ffd1)

{
    "device": {
        "applicationVersion": 0,
        "dateCode": "20240226",
        "friendlyName": "0xa4c1382b429a6c53",
        "hardwareVersion": 20,
        "ieeeAddr": "0xa4c1382b429a6c53",
        "manufacturerID": 4417,
        "manufacturerName": "Xiaomi",
        "model": "LYWSD03MMC-z",
        "networkAddress": 38212,
        "powerSource": "Battery",
        "softwareBuildID": "3001-0120",
        "stackVersion": 2,
        "type": "EndDevice",
        "zclVersion": 3
    },
    "last_seen": "2024-03-11T11:53:29+01:00",
    "linkquality": 51,
    "battery": 95.5,
    **"humidity": null,
    "temperature": null**
}

**Comment by devbis** [comment] 2024-03-12 13:42
https://github.com/devbis/z03mmc/issues/118#issuecomment-1942371299

Duplicate of https://github.com/devbis/z03mmc/issues/118

**Closed by devbis** 2024-03-12 13:42 UTC
