### ISSUE TITLE
Error when trying to update the device through OTA

### ISSUE THREAD

**Issue by gminadak** [devbis/z03mmc#119] opened 2024-02-12 17:31 UTC
After reading about the possibility to turn the device to Zigbee, I tried to update my 3 devices so I followed a guide online for the first one and updated the device from [https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html) and the other two from [https://devbis.github.io/telink-zigbee/](https://devbis.github.io/telink-zigbee/).
So now I'm in a situation that one of my devices are in an older version as shown below and the other two on the latest(???).
![Screenshot 2024-02-12 184604](https://github.com/devbis/z03mmc/assets/45330594/25e1bbac-0bc6-4e9b-b8ec-f448a9b89ff7)
I have tried everything to update the device through OTA (even to upload "ATC_ota_40000.bin")
with no luck.
Here is my folder structure inside HA
![Screenshot 2024-02-12 185421](https://github.com/devbis/z03mmc/assets/45330594/f4419e6d-59f9-4ca3-bb2d-3c952540be09)
and "my_index.json"
![Screenshot 2024-02-12 185438](https://github.com/devbis/z03mmc/assets/45330594/5900bb2b-4a86-4ed0-8131-32c50909618e)
The reason I want to upgrade is this error
![image](https://github.com/devbis/z03mmc/assets/45330594/f36f08f3-e0ef-4461-a4e4-00de2db0ad63)
and this one whenever I try to update to [1141-0203-11003001-z03mmc.zigbee]
![image](https://github.com/devbis/z03mmc/assets/45330594/7cec887f-6921-493b-8763-070c4277bd4f)
or this for [ATC_ota_40000.bin]
![image](https://github.com/devbis/z03mmc/assets/45330594/2baf2b0d-8cc2-4a88-a27d-c9ce5e5b9fe1)
Any help would be greatly appreciated

EDIT:
Here is with [z03mmc.bin]
![image](https://github.com/devbis/z03mmc/assets/45330594/101ca6f9-d66c-479e-ac3d-022814162701)
and a more readable image of the ERROR
![Screenshot 2024-02-12 194034](https://github.com/devbis/z03mmc/assets/45330594/d172ceb6-27d7-45d1-b905-ca05bcdd9fd7)

**Comment by devbis** [comment] 2024-02-13 20:15
Image type 522 means that is is a duplicate of https://github.com/devbis/z03mmc/issues/118

**Closed by devbis** 2024-02-13 20:15 UTC
