### ISSUE TITLE
it stopps during doing activation

### ISSUE THREAD

**Issue by andpaw88** [devbis/z03mmc#106] opened 2024-01-14 07:56 UTC
Hi,

i was able to connect to device, but after click "Do Activation" it gets id, token and bind key but than nothing happens.
I deleted browser cache, try to use chrome, edge also chrome on android - nothing changed. Tried also remove and reinsert the battery.

Someone can help?
<img width="1010" alt="image" src="https://github.com/devbis/z03mmc/assets/4163071/d3091d81-5e57-471f-aac9-fe899e500beb">

**Comment by devbis** [comment] 2024-01-16 06:59
Yes, according to the link above v 2.1.1_0159 can be flashed only with soldering and UART now.
Duplicate of https://github.com/devbis/z03mmc/issues/31

**Closed by devbis** 2024-01-16 06:59 UTC
